[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
Overlay=yes
ImageId=virt
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        edk2-ovmf
        libvirt
        libvirt-nss
        qemu-audio-pipewire
        qemu-char-spice
        qemu-device-display-virtio-gpu
        qemu-device-display-virtio-vga
        qemu-device-uefi-vars
        qemu-device-usb-redirect
        qemu-pr-helper
        qemu-system-x86-core
        qemu-user-binfmt
        qemu-user-static

[Build]
WithNetwork=yes
