[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0

[Build]
CacheDirectory=mkosi.cache
Incremental=yes
WithNetwork=yes
