[Distribution]
Distribution=centos
Release=10
RepositoryKeyFetch=yes

[Output]
Format=directory
Overlay=yes
ImageId=devtools
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        @Development Tools
        procps-ng
        curl
        file

[Build]
WithNetwork=yes
