[Config]
Dependencies=base

[Output]
Format=directory
Overlay=yes

[Content]
BaseTrees=%O/base
ExtraTrees=mkosi.extra.sysext
Packages=
        gamemode
        gamescope
        mangohud
        mangohud.i686
        steam
