[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
Overlay=yes
ImageId=devtools
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        @development-tools
        procps-ng
        curl
        file

[Build]
WithNetwork=yes
