[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
Overlay=yes
ImageId=docker
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        containerd.io
        docker-buildx-plugin
        docker-ce
        docker-ce-cli
        docker-compose-plugin
        docker-model-plugin

[Build]
WithNetwork=yes
