[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
Overlay=yes
ImageId=steam
OutputDirectory=mkosi.output

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        gamemode
        gamescope
        mangohud
        mangohud.i686
        steam.i686

[Build]
WithNetwork=yes
