[Output]
Format=directory

[Content]
Packages=
        @core
        @hardware-support
        glibc-langpack-en
        mesa-libEGL
        mesa-libGL
        mesa-libgbm
        mesa-vulkan-drivers
        libgcc
        libstdc++
        libomp
        numactl-libs
        pciutils-libs
        python3
        python3-libs
        elfutils-libelf
        elfutils-libs
        zlib-ng-compat
        xz-libs
