[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
ImageId=base

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
Packages=
        @core
        @hardware-support
        glibc-langpack-en
        mesa-libEGL
        mesa-libGL
        mesa-libgbm
        mesa-vulkan-drivers
        libgcc
        libstdc++
        libomp
        numactl-libs
        pciutils-libs
        python3
        python3-libs
        elfutils-libelf
        elfutils-libs
        zlib-ng-compat
        xz-libs

[Build]
WithNetwork=yes
