[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
Overlay=yes
ImageId=rocm

[Content]
Bootable=no
CleanPackageMetadata=no
WithDocs=no
SourceDateEpoch=0
BaseTrees=../base/mkosi.output/base
Packages=
        rocm-hip
        rocm-opencl
        rocm-smi

[Build]
WithNetwork=yes
